# Generated by Django 3.0.5 on 2020-04-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLvl1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100, verbose_name='Itemi de nivelul 1')),
                ('pub_date', models.DateTimeField(verbose_name='Data publicarii')),
            ],
        ),
        migrations.CreateModel(
            name='MenuLvl2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100, verbose_name='Itemi de nivelul 2')),
                ('pub_date', models.DateTimeField(verbose_name='Data publicarii')),
                ('top_lvl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.MenuLvl1')),
            ],
        ),
        migrations.CreateModel(
            name='MenuLvl3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100, verbose_name='Itemi de nivelul 3')),
                ('pub_date', models.DateTimeField(verbose_name='Data publicarii')),
                ('top_lvl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.MenuLvl2')),
            ],
        ),
    ]
