# Generated by Django 3.0.5 on 2020-04-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menulvl1',
            options={'verbose_name': 'Item de nivelul 1', 'verbose_name_plural': 'Itemi de nivelul 1'},
        ),
        migrations.AlterModelOptions(
            name='menulvl2',
            options={'verbose_name': 'Item de nivelul 2', 'verbose_name_plural': 'Itemi de nivelul 2'},
        ),
        migrations.AlterModelOptions(
            name='menulvl3',
            options={'verbose_name': 'Item de nivelul 3', 'verbose_name_plural': 'Itemi de nivelul 3'},
        ),
        migrations.AddField(
            model_name='menulvl1',
            name='numarul_de_ordine',
            field=models.IntegerField(default=1, verbose_name='Numărul de ordine în meniu'),
        ),
        migrations.AlterField(
            model_name='menulvl1',
            name='item_title',
            field=models.CharField(max_length=100, verbose_name='Item de nivelul 1'),
        ),
        migrations.AlterField(
            model_name='menulvl1',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data publicarii'),
        ),
        migrations.AlterField(
            model_name='menulvl2',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data publicarii'),
        ),
        migrations.AlterField(
            model_name='menulvl3',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data publicarii'),
        ),
    ]
