# Generated by Django 3.0.5 on 2020-04-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20200426_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulvl2',
            name='numarul_de_ordine',
            field=models.IntegerField(default=1, verbose_name='Numărul de ordine în meniu'),
        ),
        migrations.AddField(
            model_name='menulvl3',
            name='numarul_de_ordine',
            field=models.IntegerField(default=1, verbose_name='Numărul de ordine în meniu'),
        ),
    ]
