# Generated by Django 3.0.5 on 2020-04-30 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_top_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=100, verbose_name='Denumirea tagului')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Data publicarii')),
            ],
            options={
                'verbose_name': 'Tag pentru postări',
                'verbose_name_plural': 'Taguri pentru postări',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titlu')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtitlu')),
                ('body', models.TextField(verbose_name='Descrierea')),
                ('image', models.BinaryField(blank=True)),
                ('author', models.CharField(editable=False, max_length=100, verbose_name='Autor')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Data publicarii')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Tags')),
            ],
            options={
                'verbose_name': 'Postare',
                'verbose_name_plural': 'Păstări',
            },
        ),
    ]
