# Generated by Django 3.0.5 on 2020-04-30 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_posts_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_headshots/', verbose_name='Imagine '),
        ),
        migrations.AlterField(
            model_name='posts',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitlu'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.Tags'),
        ),
    ]
