# Generated by Django 3.0.5 on 2020-04-30 13:04

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_auto_20200430_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.CharField(default=django.contrib.auth.models.User, editable=False, max_length=100),
        ),
    ]
