# Generated by Django 3.0.5 on 2020-04-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0014_auto_20200430_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(to='interface.Tags'),
        ),
    ]
