# Generated by Django 3.0.5 on 2020-04-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_auto_20200430_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='interface.Tags'),
        ),
    ]
