# Generated by Django 3.0.5 on 2020-04-30 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0017_auto_20200430_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Descrierea')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Data publicarii')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Posts')),
            ],
        ),
    ]
