# Generated by Django 3.0.5 on 2020-04-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0019_auto_20200430_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Numele'),
        ),
    ]
