# Generated by Django 3.0.5 on 2020-04-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0020_auto_20200430_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='name',
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(default=1, max_length=30, verbose_name='Autorul'),
            preserve_default=False,
        ),
    ]
