# Generated by Django 3.0.5 on 2020-04-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0021_auto_20200430_2058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
